excel_headers:
- SAMPLE
- HGVS
- GENE/LOCUS
- GENE/LOCUS DESCRIPTION
- TOTAL LOCUS DEPTH
- VARIANT HETEROPLASMY
- ALT DEPTH
- REF DEPTH
- TOTAL SAMPLE DEPTH
- VARIANT QUALITY
- TIER
- COHORT COUNT
- COHORT FREQUENCY
- CHR
- POS
- REF
- ALT
- QUAL
- FILTER
- MQM_INFO
- MQMR_INFO
- QA_INFO
- QR_INFO
- SAF_INFO
- SAR_INFO
- SRF_INFO
- SRR_INFO
- SBR_INFO
- SBA_INFO
- POS_FILTER
- SBR_FILTER
- SBA_FILTER
- MQMR_FILTER
- AQR_FILTER
- ANTICODON
- GENE
- GENE BIOTYPE
- PHYLOTREE MUT
- PHYLOTREE HAPLOTYPE
- MGRB FILTER
- MGRB AN
- MGRB AC
- MGRB FREQUENCY
- MITOMAP DISEASE AC
- MITOMAP DISEASE AF
- MITOMAP DISEASE AACHANGE
- MITOMAP DISEASE HOMOPLASMY
- MITOMAP DISEASE HETEROPLASMY
- MITOMAP DISEASE PUBMED IDS
- MITOMAP DISEASE DISEASE
- MITOMAP DISEASE DISEASE STATUS
- MITOMAP DISEASE HGFL
- MITOMAP CONFIRMED MUTATIONS LOCUS
- MITOMAP CONFIRMED MUTATIONS LOCUSTYPE
- MITOMAP CONFIRMED MUTATIONS ASSOCIATEDDISEASE
- MITOMAP CONFIRMED MUTATIONS ALLELE
- MITOMAP CONFIRMED MUTATIONS AMINOACIDCHANGE
- MITOMAP CONFIRMED MUTATIONS STATUSMITOMAPCLINGEN
- MITOMAP CONFIRMED MUTATIONS LASTUPDATE
- MITOMAP MUTATIONS CODING CONTROL LOCUS
- MITOMAP MUTATIONS CODING CONTROL ALLELE
- MITOMAP MUTATIONS CODING CONTROL DISEASE
- MITOMAP MUTATIONS CODING CONTROL NUCLEOTIDECHANGE
- MITOMAP MUTATIONS CODING CONTROL AMINOACIDCHANGE
- MITOMAP MUTATIONS CODING CONTROL PLASMY
- MITOMAP MUTATIONS CODING CONTROL STATUS
- MITOMAP MUTATIONS CODING CONTROL GB FREQ
- MITOMAP MUTATIONS CODING CONTROL GB SEQS
- MITOMAP MUTATIONS CODING CONTROL REFERENCES
- MITOMAP MUTATIONS RNA LOCUS
- MITOMAP MUTATIONS RNA DISEASE
- MITOMAP MUTATIONS RNA ALLELE
- MITOMAP MUTATIONS RNA RNA
- MITOMAP MUTATIONS RNA HOMOPLASMY
- MITOMAP MUTATIONS RNA HETEROPLASMY
- MITOMAP MUTATIONS RNA STATUS
- MITOMAP MUTATIONS RNA MITOTIP
- MITOMAP MUTATIONS RNA GB FREQ
- MITOMAP MUTATIONS RNA GB SEQS
- MITOMAP MUTATIONS RNA REFERENCES
- MITOMAP POLYMORPHISMS AC
- MITOMAP POLYMORPHISMS AF
- MITOMAP POLYMORPHISMS HGFL
- MITOMAP VARIANTS CODING LOCUS
- MITOMAP VARIANTS CODING NUCLEOTIDECHANGE
- MITOMAP VARIANTS CODING CODONNUMBER
- MITOMAP VARIANTS CODING CODONPOSITION
- MITOMAP VARIANTS CODING AMINOACIDCHANGE
- MITOMAP VARIANTS CODING GB FREQ
- MITOMAP VARIANTS CODING GB SEQS
- MITOMAP VARIANTS CODING CURATEDREFERENCES
- MITOMAP VARIANTS CONTROL LOCUS
- MITOMAP VARIANTS CONTROL NUCLEOTIDECHANGE
- MITOMAP VARIANTS CONTROL GB FREQ
- MITOMAP VARIANTS CONTROL GB SEQS
- MITOMAP VARIANTS CONTROL CURATEDREFERENCES
- MITOTIP SCORE
- MITOTIP PERCENTILE
- MITOTIP QUARTILE
- MITOTIP SCORE INTERPRETATION
- MITOMAP STATUS
- COUNT
- PERCENTAGE
- GT_FORMAT
- QR_FORMAT
- AQR_FORMAT
- QA_FORMAT
- AQA_FORMAT
- INFO
- FORMAT
- gnomAD_AC_hom
- gnomAD_AC_het
- gnomAD_AF_hom
- gnomAD_AF_het
- gnomAD_max_hl
- clinvar_pathogenic
- clinvar_status
vcf_headers:
  annotations:
    ANTICODON: ANTICODON
    GENE: GENE
    GENE_BIOTYPE: GENE BIOTYPE
    PHYLOTREE_MUT: PHYLOTREE MUT
    PHYLOTREE_HAPLOTYPE: PHYLOTREE HAPLOTYPE
    MGRB_FILTER: MGRB FILTER
    MGRB_AN: MGRB AN
    MGRB_AC: MGRB AC
    MGRB_FREQUENCY: MGRB FREQUENCY
    MITOMAP_DISEASE_AC: MITOMAP DISEASE AC
    MITOMAP_DISEASE_AF: MITOMAP DISEASE AF
    MITOMAP_DISEASE_AACHANGE: MITOMAP DISEASE AACHANGE
    MITOMAP_DISEASE_HOMOPLASMY: MITOMAP DISEASE HOMOPLASMY
    MITOMAP_DISEASE_HETEROPLASMY: MITOMAP DISEASE HETEROPLASMY
    MITOMAP_DISEASE_PUBMED_IDS: MITOMAP DISEASE PUBMED IDS
    MITOMAP_DISEASE_DISEASE: MITOMAP DISEASE DISEASE
    MITOMAP_DISEASE_DISEASE_STATUS: MITOMAP DISEASE DISEASE STATUS
    MITOMAP_DISEASE_HGFL: MITOMAP DISEASE HGFL
    MITOMAP_CONFIRMED_MUTATIONS_LOCUS: MITOMAP CONFIRMED MUTATIONS LOCUS
    MITOMAP_CONFIRMED_MUTATIONS_LOCUSTYPE: MITOMAP CONFIRMED MUTATIONS LOCUSTYPE
    MITOMAP_CONFIRMED_MUTATIONS_ASSOCIATEDDISEASE: MITOMAP CONFIRMED MUTATIONS ASSOCIATEDDISEASE
    MITOMAP_CONFIRMED_MUTATIONS_ALLELE: MITOMAP CONFIRMED MUTATIONS ALLELE
    MITOMAP_CONFIRMED_MUTATIONS_AMINOACIDCHANGE: MITOMAP CONFIRMED MUTATIONS AMINOACIDCHANGE
    MITOMAP_CONFIRMED_MUTATIONS_STATUSMITOMAPCLINGEN: MITOMAP CONFIRMED MUTATIONS STATUSMITOMAPCLINGEN
    MITOMAP_CONFIRMED_MUTATIONS_LASTUPDATE: MITOMAP CONFIRMED MUTATIONS LASTUPDATE
    MITOMAP_MUTATIONS_CODING_CONTROL_LOCUS: MITOMAP MUTATIONS CODING CONTROL LOCUS
    MITOMAP_MUTATIONS_CODING_CONTROL_ALLELE: MITOMAP MUTATIONS CODING CONTROL ALLELE
    MITOMAP_MUTATIONS_CODING_CONTROL_DISEASE: MITOMAP MUTATIONS CODING CONTROL DISEASE
    MITOMAP_MUTATIONS_CODING_CONTROL_NUCLEOTIDECHANGE: MITOMAP MUTATIONS CODING CONTROL NUCLEOTIDECHANGE
    MITOMAP_MUTATIONS_CODING_CONTROL_AMINOACIDCHANGE: MITOMAP MUTATIONS CODING CONTROL AMINOACIDCHANGE
    MITOMAP_MUTATIONS_CODING_CONTROL_PLASMY: MITOMAP MUTATIONS CODING CONTROL PLASMY
    MITOMAP_MUTATIONS_CODING_CONTROL_STATUS: MITOMAP MUTATIONS CODING CONTROL STATUS
    MITOMAP_MUTATIONS_CODING_CONTROL_GB_FREQ: MITOMAP MUTATIONS CODING CONTROL GB FREQ
    MITOMAP_MUTATIONS_CODING_CONTROL_GB_SEQS: MITOMAP MUTATIONS CODING CONTROL GB SEQS
    MITOMAP_MUTATIONS_CODING_CONTROL_REFERENCES: MITOMAP MUTATIONS CODING CONTROL REFERENCES
    MITOMAP_MUTATIONS_RNA_LOCUS: MITOMAP MUTATIONS RNA LOCUS
    MITOMAP_MUTATIONS_RNA_DISEASE: MITOMAP MUTATIONS RNA DISEASE
    MITOMAP_MUTATIONS_RNA_ALLELE: MITOMAP MUTATIONS RNA ALLELE
    MITOMAP_MUTATIONS_RNA_RNA: MITOMAP MUTATIONS RNA RNA
    MITOMAP_MUTATIONS_RNA_HOMOPLASMY: MITOMAP MUTATIONS RNA HOMOPLASMY
    MITOMAP_MUTATIONS_RNA_HETEROPLASMY: MITOMAP MUTATIONS RNA HETEROPLASMY
    MITOMAP_MUTATIONS_RNA_STATUS: MITOMAP MUTATIONS RNA STATUS
    MITOMAP_MUTATIONS_RNA_MITOTIP: MITOMAP MUTATIONS RNA MITOTIP
    MITOMAP_MUTATIONS_RNA_GB_FREQ: MITOMAP MUTATIONS RNA GB FREQ
    MITOMAP_MUTATIONS_RNA_GB_SEQS: MITOMAP MUTATIONS RNA GB SEQS
    MITOMAP_MUTATIONS_RNA_REFERENCES: MITOMAP MUTATIONS RNA REFERENCES
    MITOMAP_POLYMORPHISMS_AC: MITOMAP POLYMORPHISMS AC
    MITOMAP_POLYMORPHISMS_AF: MITOMAP POLYMORPHISMS AF
    MITOMAP_POLYMORPHISMS_HGFL: MITOMAP POLYMORPHISMS HGFL
    MITOMAP_VARIANTS_CODING_LOCUS: MITOMAP VARIANTS CODING LOCUS
    MITOMAP_VARIANTS_CODING_NUCLEOTIDECHANGE: MITOMAP VARIANTS CODING NUCLEOTIDECHANGE
    MITOMAP_VARIANTS_CODING_CODONNUMBER: MITOMAP VARIANTS CODING CODONNUMBER
    MITOMAP_VARIANTS_CODING_CODONPOSITION: MITOMAP VARIANTS CODING CODONPOSITION
    MITOMAP_VARIANTS_CODING_AMINOACIDCHANGE: MITOMAP VARIANTS CODING AMINOACIDCHANGE
    MITOMAP_VARIANTS_CODING_GB_FREQ: MITOMAP VARIANTS CODING GB FREQ
    MITOMAP_VARIANTS_CODING_GB_SEQS: MITOMAP VARIANTS CODING GB SEQS
    MITOMAP_VARIANTS_CODING_CURATEDREFERENCES: MITOMAP VARIANTS CODING CURATEDREFERENCES
    MITOMAP_VARIANTS_CONTROL_LOCUS: MITOMAP VARIANTS CONTROL LOCUS
    MITOMAP_VARIANTS_CONTROL_NUCLEOTIDECHANGE: MITOMAP VARIANTS CONTROL NUCLEOTIDECHANGE
    MITOMAP_VARIANTS_CONTROL_GB_FREQ: MITOMAP VARIANTS CONTROL GB FREQ
    MITOMAP_VARIANTS_CONTROL_GB_SEQS: MITOMAP VARIANTS CONTROL GB SEQS
    MITOMAP_VARIANTS_CONTROL_CURATEDREFERENCES: MITOMAP VARIANTS CONTROL CURATEDREFERENCES
    MITOTIP_SCORE: MITOTIP SCORE
    MITOTIP_PERCENTILE: MITOTIP PERCENTILE
    MITOTIP_QUARTILE: MITOTIP QUARTILE
    MITOTIP_SCORE_INTERPRETATION: MITOTIP SCORE INTERPRETATION
    MITOMAP_STATUS: MITOMAP STATUS
    COUNT: COUNT
    PERCENTAGE: PERCENTAGE
    gnomAD_AC_hom: gnomAD_AC_hom
    gnomAD_AC_het: gnomAD_AC_het
    gnomAD_AF_hom: gnomAD_AF_hom
    gnomAD_AF_het: gnomAD_AF_het
    gnomAD_max_hl: gnomAD_max_hl
    clinvar_pathogenic: clinvar_pathogenic
    clinvar_status: clinvar_status
  format:
    AO: ALT DEPTH
    AQA: AQA_FORMAT
    AQR: AQR_FORMAT
    AQR_filter: AQR_FILTER
    DP: TOTAL SAMPLE DEPTH
    GT: GT_FORMAT
    MQMR_filter: MQMR_FILTER
    POS_filter: POS_FILTER
    QA: QA_FORMAT
    QR: QR_FORMAT
    RO: REF DEPTH
    SBA_filter: SBA_FILTER
    SBR_filter: SBR_FILTER
    VAF: VARIANT HETEROPLASMY
    q: VARIANT QUALITY
    tier: TIER
  info:
    DP: TOTAL LOCUS DEPTH
    MAP_LOCUS_DESCRIPTION: GENE/LOCUS DESCRIPTION
    MQM: MQM_INFO
    MQMR: MQMR_INFO
    MAP_LOCUS: GENE/LOCUS
    QA: QA_INFO
    QR: QR_INFO
    SAF: SAF_INFO
    SAR: SAR_INFO
    SBA: SBA_INFO
    SBR: SBR_INFO
    SRF: SRF_INFO
    SRR: SRR_INFO
